from storage.mysql.models.bank_customer import BankCustomer
from storage.mysql.models.customer_address import CustomerAddress
from storage.mysql.models.customer_kyc import CustomerKYC
from storage.mysql.models.customer_employment import CustomerEmployment
from storage.mysql.models.customer_income import CustomerIncome
from storage.mysql.models.customer_financial_profile import CustomerFinancialProfile
from storage.mysql.models.customer_credential import CustomerCredential
from storage.mysql.models.login_attempt import LoginAttempt
from storage.mysql.models.customer_session import CustomerSession
from storage.mysql.models.customer_document import CustomerDocument
from storage.mysql.models.customer_loan import CustomerLoan
from storage.mysql.models.loan_payment import LoanPayment
from storage.mysql.models.user_app_registration import UserAppRegistration
from storage.mysql.models.registration_verification import RegistrationVerification
from storage.mysql.models.login_otp_verification import LoginOtpVerification